/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FlosAccordion {
    }
    interface FlosAccordionPanel {
        /**
          * Prop der bestemmer om panelet er åbent eller ej
         */
        "expanded"?: boolean;
        /**
          * Title til accordion panel
         */
        "heading": string;
        /**
          * Plads til uddybende tekst
         */
        "subtitle"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFlosAccordionElement extends Components.FlosAccordion, HTMLStencilElement {
    }
    var HTMLFlosAccordionElement: {
        prototype: HTMLFlosAccordionElement;
        new (): HTMLFlosAccordionElement;
    };
    interface HTMLFlosAccordionPanelElement extends Components.FlosAccordionPanel, HTMLStencilElement {
    }
    var HTMLFlosAccordionPanelElement: {
        prototype: HTMLFlosAccordionPanelElement;
        new (): HTMLFlosAccordionPanelElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "flos-accordion": HTMLFlosAccordionElement;
        "flos-accordion-panel": HTMLFlosAccordionPanelElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FlosAccordion {
    }
    interface FlosAccordionPanel {
        /**
          * Prop der bestemmer om panelet er åbent eller ej
         */
        "expanded"?: boolean;
        /**
          * Title til accordion panel
         */
        "heading"?: string;
        "onExpand"?: (event: CustomEvent<string>) => void;
        /**
          * Plads til uddybende tekst
         */
        "subtitle"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "flos-accordion": FlosAccordion;
        "flos-accordion-panel": FlosAccordionPanel;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "flos-accordion": LocalJSX.FlosAccordion & JSXBase.HTMLAttributes<HTMLFlosAccordionElement>;
            "flos-accordion-panel": LocalJSX.FlosAccordionPanel & JSXBase.HTMLAttributes<HTMLFlosAccordionPanelElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
